language: node_js
node_js:
- "stable"
cache:
  directories:
    - node_modules
before_script:
- npm install
script:
- ng build --prod --aot
deploy:
  provider: surge
  domain: angular7-app-MHSU25.surge.sh
  skip_cleanup: true
